### ISSUE TITLE
Select columns button not working

### ISSUE THREAD

**Issue by manGitHub** [CCRGeneticsBranch/Oncogenomics_v2#27]
Hi, could you please check the select column button on Oncogenomics, for me it doesn't do anything. Earlier a window use to popup.
Thanks.

**Comment by hsienchao** [comment]
Can you post a screenshot? Mine is working.

**Comment by manGitHub** [comment]
Nothing happens when I click select columns, so can't reproduce screen shot. 
In somewhat related behavior of UI and backend, I am not able to access "Setting" and user admin area 


![image](https://github.com/CCRGeneticsBranch/Oncogenomics_v2/assets/16341141/c2a45fac-737a-4c9a-8ec4-91fd3a592308)

**Comment by hsienchao** [comment]
Clearing cache will resolve the issue.
